apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  selector:
    matchLabels:
      app: django
  replicas: 2
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 100Mi
---

apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
